main: de.jeff_media.JukeBoxPlus.Main
name: JukeBoxPlus
version: ${project.version}
api-version: "26.2"
author: mfnalex
#website: https://www.chestsort.de
softdepend:
  - Multiverse-Core
  - BentoBox
  - WorldGuard
  - Towny
  - Factions
  - Lands
  - PlotSquared
  - CrashClaim
